### ISSUE TITLE
Template de module

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#14]
### But

Pouvoir définir un sous-module
- de type monitoring avec hiérarchie module -> site -> visite -> observation ou tous les sites -> [module] -> visite -> observation 
- en surchargeant les configurations existantes (ex : entrée par sites, entrée par protocole, catégorie de site, visites, ...)
- avec peu de code à apporter, et en se concentrant sur les aspects spécifiques du sous-module

Permet in-fine de pouvoir améliorer les élément du template (qui vont profiter à tous les sous-modules)

#### Court terme

- Pouvoir définir les champs spécifiques pour un niveau (Catégorie)
  - edition / detail

- Travailler sur les champs

- Pouvoir redéfinir le nom de l'objet selon la circonstance et les envie des administrateurs
    - site -> circuit
    - visite -> passage

#### Long terme

- imports/exports spécifiques
- traiter les tables en dur
  - pour les layouts : se limite à mettre les bon champs dans le layout
- pour personaliser un layout de A à Z si le générique ne convient pas au contexte
- bouttons import / export
- idem pour entrée par site

### Vigilance

- à l'edition de données, ne pas effacer des clés de `data` (JSONB) provenant d'autres modules

- essayer de faire une update du dictionnnaire `data` et non une assignation

### Impératifs

Docs sur la configuration des modules et tests à jours

# TODO

## 1) Module template simple sans (trop) de redefinition

- [x] module - site - visite -observation 
  - reprise de m_protocol_test
- [x] Spécifier seulement les éléments de modules
- [x] valeurs par défaut pour les custom ????

#### TODO
  - [x] charger les templates dans les definitions
    - [x] une reference de template && une reference de module ?
      - [x] `template` et `with_template` 
    - [x] tester pour un sous module (enlever m_protocol_test) 
      - [x] `m_monitoring_test_1, `m_monitoring_test_2` 
    
## 2) Pouvoir rédéfinir certains éléments
- champs additionels
  - [ ] sur les sites
    - [ ] 1) data -> jsonb
    - [ ] 2) en dur (arbre loge ??)   

- template de layout dans la def de la page?

- nom des objects ? 

## 3) Aller plus loin
- template personalisé

### 1) 2) 3) doc et tests

**Comment by camillemonchicourt** [comment]
Dans la logique des sites multi-protocoles, je ne suis pas certain que la hiérarchie soit vraiment "module -> site -> visite -> observation" mais plutôt "site -> module -> visite -> observation", non ?

**Comment by joelclems** [comment]
L'idée serait de pouvoir avoir les deux (comme on a un peu avec le gestionnaire de site (entree par site) et le module de test.
Je commence par le classique `module -> site -> visite -> observation` et je ferai aussi l'entrée par site `site -> module -> visite -> observation`
