### ISSUE TITLE
concept diagnostic passage faune

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#37]
### Diagnostic
- [x] date
- [x] organisme
- [x] agent  
- [x] commentaire ??
### Perturbation obstacle
- [x] obstacles (+autre obstacle)
- [x] perturbation (+autre perturbation)
- [x] etat berge
- [x] ouvrage_hydrau_raccordement
- [x] ouvrage_hydrau_dimensionnement
### Amenagments
- [x] amenagement
- [x] vegetation
- [x] entretient
### Synthese
- [x] franchissabilité
- [x] interet faune

### TODO
affiner intérêt par type de faune

### Frontend
- [ ] liste
- [ ] edit
  - [ ] liste utilisateur ?
  - [ ] list organisme ? 
- [ ] details

### Test
- [ ] api

**Comment by camillemonchicourt** [comment]
Ajout du concept "Diagnostic de fonctionnalité" : 

![image](https://user-images.githubusercontent.com/4418840/232708095-6c5164f5-2b9b-4863-8208-08b984df37ab.png)

Un PAF peut avoir plusieurs diagnostics, chacun étant daté.

Ajout des diagnostics d'un PAF dans nouvel onglet, avec possibilité d'ajouter, modifier ou supprimer un diagnostic, si on a les droits d'édition sur le PAF
