### ISSUE TITLE
road to 1.2.2

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#59]
# A faire 

- check install + m_sipaf + actualiser la doc (voir #77)
- pb scroll qui reste (voir #75)
- remettre acteur serveur demo (voir #74)

- [x] comptage onglet diagnostic non effectif tant que l'onglet n'est sélectionné
- [x] protéger l'accès à `test_layout`
- [x] checker formControl.value vs formControl.getRawValue() pour les elements en disabled 
- [x] être sur que l'onglet observation ne s'affiche pas si on a pas  (test si permission_module) + documenter #42

--------------------------------------------------------------------------------------------------------------------
# Plus à Faire
- [ ] ~filtres passage faune possède des observations ?~

---------------------------------------------------------------------------------------------------------------------
# Fait
- [x] voir les priorités 2 de https://github.com/PnX-SI/gn_modulator/issues/54
  - [x] completer export objectif usage (acteur ?) 
- [x] Filtre passage Spécifique bug requete ??
- [x] create && invalidatemapsize pb
- [x] pb filtre tableau uuid
- [x] popup carte ne pas afficher des valeurs avec undefined (icone loading)
- [x] pk/pr non activé par défaut
- [x] deflate : pas de tooltip & popup ? #65 
- [x] ~se passer de ngx-mat-select-search~
  - [x] l'intégrer dans le package.json
- [x] pb quand on change nomenclature_specitificite à null pas de changement en base (serializer marshmallow) 
- [x] array & disabled pb 
- [x] zindex nominatim component pb avec la modale import
- [x] interaction carte -> liste pour observation
- [x] Filtre Possède des diagnostic**s**
- [x] check unique fields in models
- [x] geom non modifiée lors d'un update
- [x] api/interface import ref_geo (canaux, ...)?? 
- [x] filtrer les observations selon permissions sur Synthèse (voir https://github.com/PnX-SI/gn_modulator/issues/42#issuecomment-1752597582)
- [x] import 1-n (#58)
- [x] bd_topo extraire canaux
- [x] cacher/ supprimer id_role dans les acteurs
  - si suppression bien rendre obligatoire id_organisme
- [x] clarifier la maj du module: `geonature modulator update`

**Comment by camillemonchicourt** [comment]
SIPAF - Point avec le CEREMA : 

- Objectifs - Catégorie : Ajouter "PNtA loutres" et "PNA...", Attente liste CEREMA
- On supprime le champs CD_NOM des objectifs
- Import INPN - On importe tout dans un seul CA-JDD, mais on garde la trace du JDD d'origine, son UUID et ses acteurs dans le commentaire ou le champs additionnel de la Synthèse
- Occtax - Limiter la liste des taxons à la faune ? Animalia
- Occtax et autres - Pouvoir afficher les PAF sur les cartes (ref_geo.points) de manière globale et générique à GN
- Pouvoir afficher les axes sur la carte (ref_geo.linear) de manière globale et générique à GN
- Utiliser permission R de la synthèse pour lister les observations dans SIPAF (avec prise en compte sensibilité)
- Acteurs - On supprime les personnes physiques
- Import diagnostic non utile
