### ISSUE TITLE
fin de mission sipaf

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#71]
# COPIL 19/12/23

- [x] export (vue gn_exports.paf dans module Export) (#74)
- [x]  garder la même vue carto #63
- [x] zoom carte sipaf monde
  - definir `MAPCONFIG` `ZOOM_LEVEL` dans le fichier `geonature_config.toml` 
-  documentation sinp (openobs aussi) (voir #76)
-  visualisation carte (colonne tableau) application mortalité observation (voir #76)
- [x] pk/pr icone / d"sactivé par défault (cf #62)   
- [x] lineaires cannaux (prod) (api import admin) (déplacé dans #74)
- [x] préciser observation dans un rayon de 1km
- documenter import (#77)
  - fichier exemple complet ajouter acteur, usage
  - insister sur ligne multiple
  - fichier champs **Relations Multiples** 
- documenter ajout nomenclature dans feature (#77)

------------------------------------------------------------------------------------------------------------
# Retours

## S. T.
- [x] filtre spécificité à tester
- données SINP demander les données le long des route
  - (reviendrai à demander toute la métropole)
  - affiner le choix des taxon pour ne pas avoir trop de données (??????) passage faune avifaune ???
- [x] garder l'emprise de la carte tout au long de la navigation
- garder les filtres choisis (#76)
- préciser titres   
  - [x] diagnostic **de fontionalité**
  - [x] observations **sur le passage**, observation **faune** 
  - [x] **identifiant** UUID (filtres, details, form) 
  - ~utiliser mattooltip pour les titre longs ?~
- [x] filtres communes
  - corriger caractères (https://github.com/PnX-SI/RefGeo/pull/8/files) (#74)
  - [x] n'afficher que si la recherche est lancée
  - **on a pas les code postaux mais les code INSEE**
- affichage spécifique mortalité (#76)
- [x] tableau non mis à jour
- [x] tri observation `taxon` && `etat bio` ne marchent pas
- export données faune pf  #76??

## A. C.
- [x] pf details -> enlever `utilisateur`
- [x] modifier titres diag et obs (voir plus haut)
- requalification `oui` / `non` (#76)
- ouvrage hydro `oui` / `non` (#76)

## C. M.

-  [x] Tooltip des UUID. Mentionner en plus "Généré automatiquement si non renseigné"

**Comment by camillemonchicourt** [comment]
Je ne pense pas qu'il faille avoir une couleur des observations Faune différente selon la valeur du champs "Etat biologique" car ça va complexifier la lecture et compréhension et on ne veut pas faire un WebSIG.
Par contre, il faut bien que ce champs soit dans la liste des observations pour identifier facilement si une observations concerne un animal vivant ou mort.

**Comment by camillemonchicourt** [comment]
Tooltip des UUID. Mentionner en plus "Généré automatiquement si non renseigné" : 

![image](https://github.com/PnX-SI/gn_modulator/assets/4418840/f606fa38-34ff-4ced-afe3-08a5cfaadc99)
